### PR TITLE
Structure this package as a WL paclet

### PR DESCRIPTION
**Pull request by ConnorGray**
Hi @chakravala,

I was hoping I could contribute some changes to your Grassmann package which structure it as a WL paclet. These changes give some structure to this package, open the door to using `` DocumentationTools` `` to add documentation for this package, and will enable it to be used with other features which are coming down the line in WL v13.

This PR:

* adds a new PacletInfo.wl file
* moves the .wl files which make up this package into a Kernel subdirectory
* uses `` BeginPackage["Grassmann`"] `` to isolate and group the functions provided by this package into a single context

This changes this package into a Wolfram Language paclet, which is the more modern way of structuring functionality which extends the Wolfram System.

The new PacletInfo.wl file declares metadata about this paclet (it's name and version), and the "Kernel" extension declares that this paclet provides WL source code in a package named "Grassmann`".
    
This paclet can be loaded by evaluating:

```wolfram
PacletDirectoryLoad["/path/to/Grassmann.wl/"];
```
    
which makes this paclet visible to the system, but does not load the WL source code. The WL source code can now be loaded using Get (or Needs):
    
```wolfram
Get["Grassmann`"]
```
    
This works because the "Context" field of the "Kernel" extension informs Get and Needs that the "Grassmann`" context is provided by this paclet.

Just for fun, I've also added the logo.png file as the value of the "Icon" paclet info metadata, which causes that icon to appear in the PacletObject display form shown in the FE:

Screen Shot 2021-10-25 at 12 40 34 PM

### CODE REVIEW

**Comment by peeterjoot** [comment]
> The instructions for WL 12.1+ are:
> 
> ```mathematica
> PacletDirectoryLoad["/path/to/Grassmann.wl/"];
> Needs["Grassmann`"];
> ```
> 
> Prior, to 12.1, you can use:
> 
> ```mathematica
> PacletDirectoryAdd["/path/to/Grassmann.wl/"];
> Needs["Grassmann`"];
> ```
> 
> `PacletDirectoryLoad` and `PacletDirectoryAdd` do the exact same thing, the function was simply renamed in WL 12.1. `PacletDirectoryAdd` should be available going back _at least_ several major versions (I can't find off hand exactly when it was first added, but it was a while ago).

Hi Connor,

If I do this using Mathematica 12.2 (Windows), using this commit from the repo:

commit 50861f55cd2bd09816ff293293a4ef4158a4e48e (HEAD -> master, origin/master, origin/HEAD)
Author: Michael Reed <18372368+chakravala@users.noreply.github.com>
Date:   Fri Dec 17 22:34:43 2021 -0500

    improved implementation details
    
   
I get the following error:

a::shdw: Symbol a appears in multiple contexts {Grassmann`,Global`}; definitions in context Grassmann` may shadow or be shadowed by other definitions.

chakravala cannot reproduce this (he is using Mathematica 12.3).  Are there any version dependencies in your Packlet rework of this repo?

**Comment by chakravala** [comment]
Tried to help @peeterjoot with troubleshooting loading `Grassmann`, however I am not able to reproduce the issue myself.

Could @ConnorGray (cc @okofish) help out? It seems he is using v12.2 of Mathematica. When I load the Paclet in `v12.3` on my system, there is no issue. However, he seems to be having some issues. I do wonder if upgrading to v12.3 would help.

**Comment by okofish** [comment]
The shadowing warning indicates that two symbols exist with the name `a`. One is in the `` Global` `` context, which probably means it was created or used in the same session by non-Grassman-related code. The other is in the `` Grassman` `` context, such as the one used [here](https://github.com/chakravala/Grassmann.wl/blob/master/Kernel/Grassmann.wl#L130).

[Conventionally](https://reference.wolfram.com/language/tutorial/ModularityAndTheNamingOfThings.html#5934), Wolfram Language packages are structured like this:
```wl
BeginPackage["MyPackage`"] (* begins MyPackage` context *)

MyPublicFunction

Begin["`Private`"] (* begins MyPackage`Private` context *)

MyPublicFunction[x_] := myPrivateFunction[x] * 2

myPrivateFunction[y_] := y ^ 2

End[ ] (* ends MyPackage`Private` context *)

EndPackage[ ] (* ends MyPackage` context *)
```

"Declaring" `MyPublicFunction` after ``BeginPackage["MyPackage`"]`` but before ``Begin["`Private`"]`` means that the symbol `MyPublicFunction` will exist in the `` MyPackage` `` context, so it will be accessible in the user's session after the user does ``Needs["MyPackage`"]``. (There's no formal notion of "declaration" in WL; it's just that using the symbol name first in a given place causes the symbol to be created in the context that's active at that place.)
Subsequently opening a `` MyPackage`Private` `` context means that any subsequently created new symbols (e.g. `x` and `y`) end up in that context. These symbols will not be accessible to the user under their bare name, since the user never does ``Needs["MyPackage`Private`"]``, so they won't interfere with symbols in the `` Global` `` context or other contexts in the user's session.
The `` XXX`Private` `` name for such a context is convention; it can in principle have any name and need not necessarily be a "sub"-context of `` XXX` ``, although in practice it usually is.

Putting `myPrivateFunction` in the `` MyPackage`Private` `` context means that it also won't appear to the user under its bare name, although it can be accessed with the fully qualified name ``MyPackage`Private`myPrivateFunction``. This is a good way to define internal functions that are intended for use elsewhere within the package rather than by the end user.

[`Grassman.wl`](https://github.com/chakravala/Grassmann.wl/blob/master/Kernel/Grassmann.wl) is structured like this:
```wl
BeginPackage["Grassman`"] (* begins Grassman` context *)

(* ... *)
PublicFunction[v_,g_,a_List] := ...

AnotherPublicFunction[manifold_, prefix_String] := ...
(* ... *)

EndPackage[ ] (* ends Grassman` context *)
```

This way, `PublicFunction` and `AnotherPublicFunction` end up in the `` Grassman` `` context, which is good. But so do `v`, `g`, `a`, `manifold`, and `prefix`, which is not so good and likely to cause problems such as this one.

**Comment by ConnorGray** [comment]
@chakravala @peeterjoot This shadowing issue should be reproducible in any version by evaluating:

```wolfram
a = 5;

PacletDirectoryLoad["/path/to/Grassmann.wl"];

Needs["Grassmann`"]
```

As the message says, the issue is that the symbol name `a` ends up appearing in two different *visible* (on [`$ContextPath`](https://reference.wolfram.com/language/ref/$ContextPath)) contexts at the same time: `` Global` `` and `` Grassmann` ``.

The underlying issue is that the source for the Grassmann package doesn't currently distinguish between "public" and "private" symbols. When I added the `BeginPackage[".."]` statements in this PR, that told the system to put _every_ symbol used in the source code of the package in the `` Grassmann` `` context. You can see the consequence of that if you evaluate:

```wolfram
Names["Grassmann`*"]
```

which outputs a long list, that includes many symbols that are used as private local variables:

```wolfram
{a,A,a3,a3$,aa,aa$,Abs2,aD,aD$,AllocateBasis,a$,A$,b,B,b3,b3$,bas,basis,
BasisIndex,BasisIndexCalc,BasisQ,<<376>>,V$,w,W,w$,x,X,xor,xor$,x$,y,Y,y3,y3$,
y$,z,Z,ZeroQ,z$,Z$,\[DoubleStruckCapitalR],\[FivePointedStar]}
```

So, just using `BeginPackage[".."]` isn't quite the right thing to do. Instead, the package should be laid out according to the [standard package layout](https://reference.wolfram.com/language/tutorial/ModularityAndTheNamingOfThings.html#5934):

```wolfram
BeginPackage["MyPackage`"]    (* $Context == "MyPackage`" *)

(* Declare Foo here so that it ends up in the MyPackage` context *)
Foo

Begin["`Private`"]    (* $Context == "MyPackage`Private`" *)

(* a and b local variables end up in the MyPackage`Private`* context, hidden from users. *)
Foo[a_] := Module[{b}, b = a; ...]

End[]     (* End the `Private` sub context *)

EndPackage[]
```

Using this convention, the public symbols are declared first immediately after the `` BeginPackage["MyPackage`"] `` statement, and then `` Begin["`Private`"] `` is used so that the remaining symbols end up in the `` MyPackage`Private` `` context (which is not visible by default to anyone who loads the package using `` Needs["MyPackage`"] ``.

I didn't make this additional transformation in this PR because I don't have the subject matter expertise to make a reasonable determination about which symbols in your package should be considered public vs. private.

To fix this shadowing warning, and to make the `` Names["Grassmann`*"] `` result cleaner, you should wrap every file in paired `` Begin["`Private`"] `` and ``End[]`` statements near the top and bottom respectively of the file, and list the symbols you want to be public at the top of the file after the `BeginPackage` statement but before the `Begin` statement.

Let me know if this helps clear things up, and apologies for the apparent subtlety of this change: scoping is fully dynamic in Wolfram Language, so defining a package is an inherently stateful operation. I'm happy to help if you have additional questions about how WL packages are conventionally structured.

See Also: [`BeginPackage`](https://reference.wolfram.com/language/ref/BeginPackage), [`Begin`](https://reference.wolfram.com/language/ref/Begin), [`$Context`](https://reference.wolfram.com/language/ref/$Context), [`$ContextPath`](https://reference.wolfram.com/language/ref/$ContextPath), [Modularity and The Naming of Things](https://reference.wolfram.com/language/tutorial/ModularityAndTheNamingOfThings.html#27982)

**Comment by okofish** [comment]
@ConnorGray We wrote the exact same explanation! Now I can feel more confident that it was the right one 😆

**Comment by ConnorGray** [comment]
@okofish Indeed! After I posted the comment and noticed I got an email notification for this thread and saw your name and comment, my first gut reaction was wondering how in the world I had accidentally posted a comment using your GitHub account! 😂

**Comment by chakravala** [comment]
Thanks hope that helps @peeterjoot work things out.

Currently, I am intending to keep developing the repository without any private namespaces, for development purposes. I wanted to mainly focus my efforts on the code and not think about the packaging yet.

**Comment by peeterjoot** [comment]
@ConnorGray I had no symbol a in my notebook (and also did a kernel restart to clean house.).  As an experiment, I tried calling PacletDirectoryUnload, and then redid the PacletDirectoryLoad.  

It almost seems like the Paclet was conflicting with itself.  Here are the steps that I used to get into this situation:

1)
From a WSL2 ubuntu shell (Windows 11):
git clone  git@github.com:chakravala/Grassmann.wl.git
mv Grassmann.wl /mnt/c/Users/peete/AppData/Roaming/Mathematica/Applications/Grassmann.wl
\# i.e.: C:\Users\peete\AppData\Roaming\Mathematica\Applications\Grassmann.wl

2) reported an issue to @chakravala after trying PacletDirectoryLoad + Get for the Grassmann.wl package.

3) tried git pull in the Grassmann.wl repo to grab the updates.  This failed, as the mv from the ubuntu WSL2 filesystem to the NTFS filesystem seemed to mess up git metadata.  I moved Grassmann.wl to different file name (Grassmann.wl.orig) and then recloned.

4) Tried PacletDirectoryLoad again.  I believe this failed (Mathematica seemed to have somehow figured out that the directory had been renamed.)  I deleted it and then redid the PacletDirectoryLoad.  That worked, but then I got the symbol conflicts on Get.

I can imagine the answer to this is "Well, don't do that!"

With the PacletDirectoryUnload[], and then a new PacletDirectoryLoad[], I no longer get the symbol conflicts.

**Pull request merged**
